apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dpeloyment
  namespace: argocd 
spec:
  project: default

  source: 
    repoURL: https://github.com/muneebxyz/Project-QUIZ.git
    targetRevision: HEAD
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: quiz-app

  syncPolicy:

      syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      automated:
        selfHeal: true
        prune: true