---
apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
spec:
  selector:
    app: quiz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort