apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - quiz
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: quiz-image
        image: muneebxyz/simple-quiz-app:main-ba0eca4
        ports:
        - containerPort: 5000

                               