name: Building and pushing docker image on every build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 docker:
  runs-on: ubuntu-latest
  steps:


    - name: Checkout
      uses: actions/checkout@v3

    - name: Get the branch name
      id: get_branch_name
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
        echo "::set-output name=branch_name::$BRANCH_NAME"

    - name: Get the short commit ID
      id: get_short_commit_id
      run: |
        SHORT_COMMIT_ID=$(git rev-parse --short HEAD)
        echo "::set-output name=short_commit_id::$SHORT_COMMIT_ID"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: muneebxyz/simple-quiz-app:${{ steps.get_branch_name.outputs.branch_name }}-${{ steps.get_short_commit_id.outputs.short_commit_id }}



    
