name: Building and pushing docker image on every build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 docker:
  runs-on: ubuntu-latest
  steps:


    - name: Checkout
      uses: actions/checkout@v3


    - name: Get the latest commit ID
      id: get_commit_id
      run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: muneebxyz/simple-quiz-app/:QUIZ_COMMIT#${{steps.get_commit_id.outputs.commit_id }}




    
